### ISSUE TITLE
Energy and Ammo meters are not exactly right

### ISSUE THREAD

**Issue by pomle** [pomle/megamanjs#27]
* Should only show full when exactly 100%.
* Should only show empty when exactly 0%.

**Comment by keenanjohnson** [comment]
You resolved this in this commit correct?

https://github.com/pomle/megamanjs/commit/7fd674c0b9872d708bb41462df7f2b0911a43626#diff-42724837fd5ee5fea4b331ce02ccdc87

**Comment by pomle** [comment]
I thought I did, but I don't think they are behaving correctly. There is an edge case on either end of the scale, but I have no proof currently.

**Comment by pomle** [comment]
Fixed in https://github.com/pomle/megamanjs/pull/105
